image: docker:latest
services:
- docker:dind

stages:
- build
- puller

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - exit 0
  - docker login -u "$DOCKER_REGISTRY_USER" -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_URL

build:
  stage: build
  script:
    - docker build --pull --build-arg CI_PROJECT_URL=$CI_PROJECT_URL -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    - exit 0
    - docker build --pull --build-arg CI_PROJECT_URL=$CI_PROJECT_URL -t "$DOCKER_REGISTRY_IMAGE" .
    - docker push $DOCKER_REGISTRY_IMAGE
