version: '3'

services:
  eclipse_installer:
    build: .
    image: nouchka/oomph
    environment:
      - DISPLAY=unix$DISPLAY
      - ECLIPSE_VERSION=katagena-oxygen
    volumes:
      - ~/.ssh/:/home/developer/.ssh/:ro
      - ~/.gitconfig:/home/developer/.gitconfig:ro
      - ~/.gitignore:/home/developer/.gitignore:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./setup/:/home/developer/setup/
      - installer:/opt/eclipse-installer/ ##volume for the installer to keep update

volumes:
  installer:
    driver: local

##  workspace:
##    driver: local
##  eclipse:
##    driver: local
##  eclipse_configuration:
##    driver: local
##  p2_configuration:
##    driver: local

