version: '3'

services:
  eclipse_installer:
    build: .
    image: nouchka/oomph:php7
    container_name: "neon"
    hostname: "eclipse"
    environment:
      - DISPLAY=unix$DISPLAY
      - ECLIPSE_VERSION=katagena-php7
    volumes:
      - ~/.ssh/:/home/developer/.ssh/:ro
      - ~/.gitconfig:/home/developer/.gitconfig:ro
      - ~/.gitignore:/home/developer/.gitignore:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - eclipse:/home/developer/eclipse/ ##volume for differents eclipses versions
      - installer:/opt/eclipse-installer/ ##volume for the installer to keep update
      - ~/Desktop/workspace/:/home/developer/workspace/
  setup:
    image: nouchka/lighttpd
    volumes:
      - ./setup:/var/www/localhost/htdocs

volumes:
  installer:
    driver: local
  eclipse:
    driver: local
