#!/usr/bin/env bash

if [ "$DOCKER_TAG" = "latest" ]; then
	BASE_IMAGE=ubuntu:xenial
elif [ "$DOCKER_TAG" = "php7" ]; then
	BASE_IMAGE=ubuntu:xenial
elif [ "$DOCKER_TAG" = "php5" ]; then
	BASE_IMAGE=debian:jessie
else
	echo "Need to specify base image"
	exit 1
fi

docker build -t ${IMAGE_NAME} \
	--build-arg=BASE_IMAGE=$BASE_IMAGE \
	--build-arg=DOCKER_TAG=$DOCKER_TAG \
	.
